name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend image
        run: docker build -t backend-app ./backend

      - name: Run unit tests (no cache)
        run: docker run backend-app pytest -p no:cacheprovider

      # ğŸ” Login to Docker Hub
      - name: Docker Hub Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # ğŸš€ Tag and Push Image
      - name: Tag & Push Image to Docker Hub
        run: |
          docker tag backend-app ${{ secrets.DOCKER_USERNAME }}/backend-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-app:latest
