name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ğŸ”¹ Build Backend
      - name: Build backend image
        run: docker build -t backend-app ./backend

      # ğŸ”¹ Run Backend Tests
      - name: Run backend unit tests
        run: docker run backend-app pytest -p no:cacheprovider

      # ğŸ”¹ Build Frontend
      - name: Build frontend image
        run: docker build -t frontend-app ./frontend

      # ğŸ” Docker Hub Login
      - name: Docker Hub Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # ğŸš€ Push Backend Image
      - name: Push backend image
        run: |
          docker tag backend-app ${{ secrets.DOCKER_USERNAME }}/backend-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-app:latest

      # ğŸš€ Push Frontend Image
      - name: Push frontend image
        run: |
          docker tag frontend-app ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest
